### ISSUE TITLE
using PyPlot

### ISSUE THREAD

**Issue by dflemin3** [jlustigy/ExoJulia#2]
For testing functions, plotting, etc, it would be useful to have PyPlot in various places, but where do we put it?  The first "using PyPlot" call is slow due to compilation, so it might be worthwhile to have it called with the "using ExoJulia" call.

**Comment by jlustigy** [comment]
We've removed PyPlot from the current ExoJulia package. Going forward, we'll doing all the plotting exterior to ExoJulia (Unless we decide to build a plotting package later...).
